import type { Express } from 'express';
import { authMiddleware } from '../middleware/auth.middleware.js';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import clientRoutes from './client.routes.js';
import invoiceRoutes from './invoice.routes.js';
import quoteRoutes from './quote.routes.js';
import paymentRoutes from './payment.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import settingsRoutes from './settings.routes.js';
import recurringRoutes from './recurring.routes.js';
import aiRoutes from './ai.routes.js';
import bankAccountRoutes from './bank-account.routes.js';
import transactionRoutes from './transaction.routes.js';
import chatRoutes from './chat.routes.js';
import jofotaraRoutes from './jofotara.routes.js';
import reportRoutes from './report.routes.js';
import dailySummaryRoutes from './daily-summary.routes.js';
import emailTemplateRoutes from './email-template.routes.js';
import trackingRoutes from './tracking.routes.js';
import emailLogRoutes from './email-log.routes.js';
import employeeRoutes from './employee.routes.js';
import payrollRoutes from './payroll.routes.js';
import partnerExpenseRoutes from './partner-expenses.routes.js';
import chartOfAccountsRoutes from './chart-of-accounts.routes.js';

export function mountRoutes(app: Express) {
  app.use('/api/auth', authRoutes);
  app.use('/api/users', authMiddleware, userRoutes);
  app.use('/api/clients', authMiddleware, clientRoutes);
  app.use('/api/invoices', authMiddleware, invoiceRoutes);
  app.use('/api/quotes', authMiddleware, quoteRoutes);
  app.use('/api/payments', authMiddleware, paymentRoutes);
  app.use('/api/dashboard', authMiddleware, dashboardRoutes);
  app.use('/api/settings', authMiddleware, settingsRoutes);
  app.use('/api/recurring', authMiddleware, recurringRoutes);
  app.use('/api/ai', authMiddleware, aiRoutes);
  app.use('/api/bank-accounts', authMiddleware, bankAccountRoutes);
  app.use('/api/transactions', authMiddleware, transactionRoutes);
  app.use('/api/chat', authMiddleware, chatRoutes);
  app.use('/api/jofotara', authMiddleware, jofotaraRoutes);
  app.use('/api/reports', authMiddleware, reportRoutes);
  app.use('/api/daily-summary', authMiddleware, dailySummaryRoutes);
  app.use('/api/email-templates', authMiddleware, emailTemplateRoutes);
  app.use('/api/tracking', trackingRoutes); // Public — no auth
  app.use('/api/email-log', authMiddleware, emailLogRoutes);
  app.use('/api/employees', authMiddleware, employeeRoutes);
  app.use('/api/payroll', authMiddleware, payrollRoutes);
  app.use('/api/partner-expenses', authMiddleware, partnerExpenseRoutes);
  app.use('/api/accounts', authMiddleware, chartOfAccountsRoutes);
}
